import { Category } from '../../types';

interface CategoriesType {
  [id: string]: Category;
}

export const defaultCategories: CategoriesType = {
  d172b3121: {
    id: 'd172b3121',
    name: 'Food and drinks',
    link: 'food_and_drinks',
    type: 'expense',
    icon: 'shop',
    color: '#3E2723',
    createdAt: Date.now(),
  },
  d172b5722: {
    id: 'd172b5722',
    name: 'Shopping',
    link: 'shopping',
    type: 'expense',
    icon: 'credit-card',
    color: '#CE93D8',
    createdAt: Date.now(),
  },
  d172b6c23: {
    id: 'd172b6c23',
    name: 'Transports',
    link: 'transports',
    type: 'expense',
    icon: 'bus-front-12',
    color: '#455A64',
    createdAt: Date.now(),
  },
  d172ba724: {
    id: 'd172ba724',
    name: 'Home',
    link: 'home',
    type: 'expense',
    icon: 'building',
    color: '#A5D6A7',
    createdAt: Date.now(),
  },
  d172bc525: {
    id: 'd172bc525',
    name: 'Bills and taxes',
    link: 'bills_and_taxes',
    type: 'expense',
    icon: 'money-coins',
    color: '#E91E63',
    createdAt: Date.now(),
  },
  d172bdd26: {
    id: 'd172bdd26',
    name: 'Fun',
    link: 'fun',
    type: 'expense',
    icon: 'satisfied',
    color: '#26C6DA',
    createdAt: Date.now(),
  },
  d172bf027: {
    id: 'd172bf027',
    name: 'Car',
    link: 'car',
    type: 'expense',
    icon: 'delivery-fast',
    color: '#EF6C00',
    createdAt: Date.now(),
  },
  d172c0328: {
    id: 'd172c0328',
    name: 'Travels',
    link: 'travels',
    type: 'expense',
    icon: 'spaceship',
    color: '#FBC02D',
    createdAt: Date.now(),
  },
  d172c1529: {
    id: 'd172c1529',
    name: 'Family and personal',
    link: 'family_and_personal',
    type: 'expense',
    icon: 'single-02',
    color: '#3E2723',
    createdAt: Date.now(),
  },
  d172c5f210: {
    id: 'd172c5f210',
    name: 'Health',
    link: 'health',
    type: 'expense',
    icon: 'ambulance',
    color: '#FFEB3B',
    createdAt: Date.now(),
  },
  d172c76211: {
    id: 'd172c76211',
    name: 'Education',
    link: 'education',
    type: 'expense',
    icon: 'hat-3',
    color: '#00796B',
    createdAt: Date.now(),
  },
  d172c97212: {
    id: 'd172c97212',
    name: 'Groceries',
    link: 'groceries',
    type: 'expense',
    icon: 'basket',
    color: '#A7FFEB',
    createdAt: Date.now(),
  },
  d172cab213: {
    id: 'd172cab213',
    name: 'Gifts',
    link: 'gifts',
    type: 'expense',
    icon: 'favourite-28',
    color: '#424242',
    createdAt: Date.now(),
  },
  d172cbf214: {
    id: 'd172cbf214',
    name: 'Sport and free time',
    link: 'sport_and_free_time',
    type: 'expense',
    icon: 'controller',
    color: '#1976D2',
    createdAt: Date.now(),
  },
  d172cd3215: {
    id: 'd172cd3215',
    name: 'Beauty',
    link: 'beauty',
    type: 'expense',
    icon: 'bag-17',
    color: '#FFF59D',
    createdAt: Date.now(),
  },
  d172ce6216: {
    id: 'd172ce6216',
    name: 'Work',
    link: 'work',
    type: 'expense',
    icon: 'briefcase-24',
    color: '#880E4F',
    createdAt: Date.now(),
  },
  d172d1e217: {
    id: 'd172d1e217',
    name: 'Others',
    link: 'others',
    type: 'expense',
    icon: 'tag',
    color: '#C5E1A5',
    createdAt: Date.now(),
  },
  d172d32218: {
    id: 'd172d32218',
    name: 'Recurrent',
    link: 'recurrent',
    type: 'expense',
    icon: 'calendar-grid-58',
    color: '#EF9A9A',
    createdAt: Date.now(),
  },
};
