// Authentication
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// Categories
export const CATEGORIES_REQUEST_SUCCESS = "CATEGORIES_REQUEST_SUCCESS";
export const CATEGORIES_REQUEST_ERROR = "CATEGORIES_REQUEST_ERROR";

// Loader
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

